# Лабораторная работа №1
## Выполнил студент группы ГРУППА ФИО

### Оглавление
1. [Задание 1](#Задание-№1)
2. [Задание 2](#Задание-№2)
3. [Задание 3](#Задание-№3)
4. [Вывод](#Вывод)

### Задание №1
<i> Вызвать функцию print() и передать туда строку Hello, World! </i>

In [ ]:
print("Hello, world!")

### Задание №2
Написать генератор случайных матриц(многомерных), который принимает
опциональные параметры <b>m</b>, <b>n</b>, <b>min_limit</b>, <b>max_limit</b>, где <b>m</b> и <b>n</b> указывают размер
матрицы, а <b>min_lim</b> и <b>max_lim</b> - минимальное и максимальное значение для
генерируемого числа.

In [2]:
import random
import numpy as np
import time

In [33]:
def create_matrix(m, n, min_limit, max_limit):
    A = np.random.randint(min_limit, max_limit, size=(m, n))
    return A

user_m = int(input("Введите количество строк: "))
user_n = int(input("Введите количество столбцов: "))
user_min_limit = int(input("Введите минимальное значение элемента: "))
user_max_limit = int(input("Введите максимальное значение элемента: "))

matrix = create_matrix(user_m, user_n, user_min_limit, user_max_limit)
print(matrix)

Введите количество строк: 3
Введите количество столбцов: 6
Введите минимальное значение элемента: 12
Введите максимальное значение элемента: 4


ValueError: low >= high

Генератор случайных матриц с помощью циклов

In [28]:
def create_matrix(m, n, min_limit, max_limit):
    A = np.random.randint(min_limit, max_limit, size=(m, n))
    return A

user_m = int(input("Введите количество строк: "))
user_n = int(input("Введите количество столбцов: "))
user_min_limit = int(input("Введите минимальное значение элемента: "))
user_max_limit = int(input("Введите максимальное значение элемента: "))

matrix_2 = create_matrix(user_m, user_n, user_min_limit, user_max_limit)
matrix

Введите количество строк: 3
Введите количество столбцов: 5
Введите минимальное значение элемента: 12
Введите максимальное значение элемента: 34


array([[30, 18, 21, 13, 26, 17],
       [35, 21, 38, 13, 12, 21],
       [33, 32, 38, 21, 25, 44]])

### Задание №3
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [29]:
import copy
import timeit

In [23]:
matrix_copy_1 = copy.deepcopy(matrix)
print(matrix_copy,'\n')

def selection_sort_matrix(matrix):
    for i in range(len(matrix)):
        min_index = i
        for j in range(i+1, len(matrix)):
            if matrix[j][0] < matrix[min_index][0]:
                min_index = j
        matrix[i], matrix[min_index] = matrix[min_index], matrix[i]
    return matrix


print(selection_sort_matrix(matrix))

start = timeit.default_timer()
end = timeit.default_timer()

print("--- {0} ms ---".format((end - start) * 1000))

[[1 3 6 7]
 [1 3 6 7]
 [1 3 6 7]] 

[[1 3 6 7]
 [1 3 6 7]
 [1 3 6 7]]
--- 0.02300000005561742 ms ---


In [32]:
matrix_copy_2 = copy.deepcopy(matrix_2)

def insertion_sort_matrix(matrix):
    for i in range(len(matrix)):
        for j in range(1, len(matrix[i])):
            key = matrix[i][j]
            k = j - 1
            while k >= 0 and matrix[i][k] > key:
                matrix[i][k + 1] = matrix[i][k]
                k -= 1
            matrix[i][k + 1] = key
    return matrix

print(insertion_sort_matrix(matrix_2))

start = timeit.default_timer()
end = timeit.default_timer()

print("--- {0} ms ---".format((end - start) * 1000))

[[12 18 23 24 25]
 [19 20 24 25 33]
 [13 18 20 25 30]] 

[[12 18 23 24 25]
 [19 20 24 25 33]
 [13 18 20 25 30]]
--- 0.023399999918183312 ms ---


In [31]:
matrix_copy_3 = copy.deepcopy(matrix_2)


def bubble_sort_matrix(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])-1):
            for k in range(len(matrix[i])-j-1):
                if matrix[i][k] > matrix[i][k+1]:
                    matrix[i][k], matrix[i][k+1] = matrix[i][k+1], matrix[i][k]
    return matrix

print(bubble_sort_matrix(matrix_2))

start = timeit.default_timer()
end = timeit.default_timer()

print("--- {0} ms ---".format((end - start) * 1000))

[[1 3 6 7]
 [1 3 6 7]
 [1 3 6 7]] 

[[12 18 23 24 25]
 [19 20 24 25 33]
 [13 18 20 25 30]]
--- 0.024700000267330324 ms ---


In [ ]:
# Сортировка Шелла.
start_time = time.time()
#TODO
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

In [ ]:
# Быстрая сортировка.
start_time = time.time()
#TODO
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))
    

In [ ]:
# Турнирная сортировка.
start_time = time.time()
#TODO
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

### Вывод
